# -*- coding: utf-8 -*-
"""DS 6th Text analysis for Clinical data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxQm_lwP02q-aWE9EagVvPk8tB8GwDnL
"""

!pip install scispacy render

!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_sm-0.5.4.tar.gz
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_md-0.5.4.tar.gz
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bc5cdr_md-0.5.4.tar.gz

import pandas as pd
mtsample_df = pd.read_csv("mtsamples.csv")

print(mtsample_df.head())
print(mtsample_df.info())
print(mtsample_df.shape)

import en_core_sci_sm
import en_core_sci_md

text = mtsample_df['transcription'][10]

text

nlp_sm = en_core_sci_sm.load()
doc = nlp_sm(text)
from spacy import displacy

displacy.render(doc, style='ent', jupyter=True)

print("TEXT", "START", "END", "ENTITY TYPE")
for ent in doc.ents:
  print(ent.text, ent.start_char, ent.end_char, ent.label_)

nlp_md = en_core_sci_md.load()
doc = nlp_md(text)
#Display resulting entity extraction
displacy_image = displacy.render(doc, jupyter=True,style='ent')

import en_ner_bc5cdr_md
nlp_bc = en_ner_bc5cdr_md.load()
doc = nlp_bc(text)
#Display resulting entity extraction
displacy_image = displacy.render(doc, jupyter=True,style='ent')

print("TEXT", "START", "END", "ENTITY TYPE")
for ent in doc.ents:
  print(ent.text, ent.start_char, ent.end_char, ent.label_)